apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: mesh
build:
  artifacts:
  - image: backend
    context: backend
    docker:
      dockerfile: Dockerfile
  - image: frontend
    context: frontend
    docker:
      dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: backend
        chartPath: backend/helm
        artifactOverrides:
          image: backend
        imageStrategy:
          helm: {}
      - name: frontend
        chartPath: frontend/helm
        artifactOverrides:
          image: frontend
        imageStrategy:
          helm: {}
