name: Mesh CI/CD
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  pipeline:
    name: Skaffold Build
    runs-on: ubuntu-20.04
    steps:
      - name: Build Container Images
        uses: hiberbee/github-action-skaffold@1.23.0
        with:
          command: build
